import { Dimensions, StyleSheet } from "react-native"
import { COLORS } from "@/constants/colors"

export const profileStyles = StyleSheet.create({
    container: {
        flex: 1,
        width: "100%",
        height: "100%",
        backgroundColor: COLORS.primary,
        justifyContent: "flex-end",
        alignItems: "center",
    },
    profilePicture: {
        width: "100%",
        height: "100%",
        borderRadius: 80,
        backgroundColor: COLORS.white,
    },
    outerProfilePicture: {
        position: "absolute",
        left: 30,
        top: -70,
        alignSelf: "center",
        width: 140,
        height: 140,
        borderRadius: 70,
        backgroundColor: COLORS.primary,
        justifyContent: "center",
        alignItems: "center",
        overflow: "hidden",
        borderWidth: 5,
        borderColor: COLORS.background,
    },
    profilePictureContainer: {
        position: "absolute",
        top: -60,
        left: 40,
        alignSelf: "center",
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: COLORS.white,
        justifyContent: "center",
        alignItems: "center",
        overflow: "hidden",
        borderWidth: 3,
        borderColor: COLORS.primary,
    },
    cardProfile: {
        width: "100%",
        backgroundColor: COLORS.background,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        padding: 20,
        justifyContent: "flex-start",
        alignItems: "center",
    },
    changeImageContainer: {
        width: "100%",
        alignItems: "flex-end",   
    },
    changeImage: {
        width: "auto",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: COLORS.primary,
        padding: 10,
        borderRadius: 15,
        flexDirection: "row",
        gap: 10,
        shadowColor: COLORS.shadow,
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.25,
        shadowRadius: 1,
        elevation: 11,
    },
    textChangeImage: {
        fontSize: 16,
        fontWeight: "bold",
        color: COLORS.white,
    },
    icons: {
        width: 20,
        height: 20,
        tintColor: COLORS.white,
    },
    namaUserContainer: {
        width: "100%",
        marginTop: 20,
    },
    rowContainer: {
        flexDirection: "row",
        justifyContent: "space-between",  
    },
    namaUser: {
        fontSize: 20,
        fontWeight: "bold",
        color: COLORS.textPrimary,
    },
    statusBadge: {
        backgroundColor: COLORS.tertiary,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
    },
    statusText: {
        color: COLORS.white,
        fontSize: 12,
        fontWeight: "600",
    },
    roleText: {
        fontSize: 13,
        color: COLORS.textSecondary,
        fontWeight: "500",
        marginTop: 2,
    },
    idText: {
        fontSize: 13,
        color: COLORS.tertiary,
        marginTop: 2,
    },
    cardPickerContainer: {
        marginTop: 20,
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
    },
    buttonPicker: {
        width: "30%",
        backgroundColor: COLORS.white,
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 20,
        alignItems: "center",
        shadowColor: COLORS.shadow,
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.25,
        shadowRadius: 1,
        elevation: 11,
    },
    modeText: {
        fontSize: 16,
        color: COLORS.primary,
    },
});