import { Dimensions, StyleSheet } from "react-native"
import { COLORS } from "@/constants/colors"

export const profileStyles = StyleSheet.create({
    container: {
        width: "100%",
        backgroundColor: COLORS.primary,
        paddingTop: 120,
    },
    profilePicture: {
        width: "100%",
        height: "100%",
        borderRadius: 80,
        backgroundColor: COLORS.white,
    },
    outerProfilePicture: {
        position: "absolute",
        left: 30,
        top: -70,
        alignSelf: "center",
        width: 140,
        height: 140,
        borderRadius: 70,
        backgroundColor: COLORS.primary,
        justifyContent: "center",
        alignItems: "center",
        overflow: "hidden",
        borderWidth: 5,
        borderColor: COLORS.background,
    },
    profilePictureContainer: {
        position: "absolute",
        top: -60,
        left: 40,
        alignSelf: "center",
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: COLORS.white,
        justifyContent: "center",
        alignItems: "center",
        overflow: "hidden",
        borderWidth: 3,
        borderColor: COLORS.primary,
    },
    cardProfile: {
        width: "100%",
        backgroundColor: COLORS.background,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        padding: 20,
        paddingTop: 40,
        alignItems: "center",
    },
    changeImageContainer: {
        width: "100%",
        alignItems: "flex-end",   
    },
    changeImage: {
        width: "auto",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: COLORS.primary,
        padding: 10,
        borderRadius: 15,
        flexDirection: "row",
        gap: 10,
        shadowColor: COLORS.shadow,
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.25,
        shadowRadius: 1,
        elevation: 11,
    },
    textChangeImage: {
        fontSize: 16,
        fontWeight: "bold",
        color: COLORS.white,
    },
    icons: {
        width: 20,
        height: 20,
        tintColor: COLORS.white,
    },
    namaUserContainer: {
        width: "100%",
        marginTop: 20,
    },
    rowContainer: {
        flexDirection: "row",
        justifyContent: "space-between",  
    },
    namaUser: {
        fontSize: 20,
        fontWeight: "bold",
        color: COLORS.textPrimary,
    },
    statusBadge: {
        backgroundColor: COLORS.tertiary,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
    },
    statusText: {
        color: COLORS.white,
        fontSize: 12,
        fontWeight: "600",
    },
    roleText: {
        fontSize: 13,
        color: COLORS.textSecondary,
        fontWeight: "500",
        marginTop: 2,
    },
    idText: {
        fontSize: 13,
        color: COLORS.tertiary,
        marginTop: 2,
    },
    cardPickerContainer: {
        marginTop: 20,
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
    },
    buttonPicker: {
        width: "auto",
        backgroundColor: COLORS.white,
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 20,
        alignItems: "center",
        shadowColor: COLORS.shadow,
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.25,
        shadowRadius: 1,
        elevation: 11,
    },
    modeText: {
        fontSize: 16,
        color: COLORS.primary,
    },
    menuPickerContainer: {
        width: "100%",
        paddingHorizontal: 16,
        paddingVertical: 10,
        backgroundColor: COLORS.white,
        borderRadius: 10,
        marginTop: 0,
        shadowColor: COLORS.shadow,
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.1,
        shadowRadius: 1,
        elevation: 4,
        gap: 5,
    },
    menuPicker: {
        paddingVertical: 16,
        borderBottomColor: COLORS.border,
        borderStyle: "solid",
        borderBottomWidth: 1,
        flexDirection: 'row',
        justifyContent: "space-between",
        alignItems: "center",
    },
    menu: { 
        flexDirection: "row", 
        justifyContent: "center", 
        alignItems: "center",
        gap: 16
    },
    imagePicker: {
        width: 20,
        height: 20,
        tintColor: COLORS.tertiary,
    },
    textPicker: {
        fontSize: 16,
        color: COLORS.tertiary,
        marginTop: 2,
    },
    actionImagePicker: {
        width: 12,
        height: 12,
        tintColor: COLORS.tertiary,
    },
    header: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        height: 60,
        backgroundColor: COLORS.primary,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingVertical: 10,
        zIndex: 10,
    },
    headerTitle: {
        fontFamily: "poppins",
        fontSize: 16,
        fontWeight: "bold",
        color: COLORS.white
    },
    subHeaderDetail: {
        alignItems: "center",
        marginBottom: 10,
        gap: 5,
    },
    detailTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginTop: 10,
        color: COLORS.textPrimary
    },
    iconPlace: { 
        width: 32, 
        height: 32, 
        borderRadius: 40, 
        backgroundColor: COLORS.white, 
        justifyContent: "center", 
        alignItems: "center",
        marginRight: 10 
    },
    iconBack: {
        width: 16,
        height: 16,
        tintColor: COLORS.primary,
    },
    firstContainer: {
        width: "90%",
        gap: 16,
    },
    titleFirst: {
        fontSize: 28,
        color: COLORS.primary,
        fontWeight: "bold",
    },
    descriptionFirst: {
        fontSize: 14,
        color: COLORS.textMuted,
    },
    subHeaderContainer: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
    },
    subHeader: {
        height: "auto",
        width: "48%",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: COLORS.white,
        paddingVertical: 16,
        marginVertical: 15,
        borderRadius: 15,
        shadowColor: COLORS.shadow,
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.1,
        shadowRadius: 1,
        elevation: 4,
        gap: 5,
    },
    logoAbsen: {
        width: 24,
        height: 24,
        tintColor: COLORS.tertiary,
    },
    logoCuti: {
        width: 24,
        height: 24,
        tintColor: COLORS.tertiary,
    },
    titleAbsen: {
        color: COLORS.tertiary,
        fontSize: 16,
        fontWeight: "600",
    },
    titleCuti: {
        color: COLORS.tertiary,
        fontSize: 16,
        fontWeight: "600",
    },
    textAbsen: {
        color: COLORS.tertiary,
    },
    textCuti: {
        color: COLORS.tertiary,
    },
});