import { Absensi } from "../types/types";

export const dummyAbsensi: Absensi[] = [
    {
        id: "User-001-BudiSantoso",
        name: "Budi Santoso",
        workStatus: "Work From Home",
        majorRole: "Karyawan",
        minorRole: "HR",
        date: "2025-10-21",
        checkIn: "08:02",
        checkOut: "17:00",
    },
    {
        id: "User-002-SitiRahmawati",
        name: "Siti Rahmawati",
        workStatus: "Work From Office",
        majorRole: "Karyawan",
        minorRole: "Finance",
        date: "2025-10-21",
        checkIn: "07:55",
        checkOut: "16:45",
    },
    {
        id: "User-003-AhmadFauzi",
        name: "Ahmad Fauzi",
        workStatus: "Hybrid",
        majorRole: "Supervisor",
        minorRole: "Operations",
        date: "2025-10-21",
        checkIn: "08:10",
        checkOut: "17:05",
    },
    {
        id: "User-004-DewiLestari",
        name: "Dewi Lestari",
        workStatus: "Work From Home",
        majorRole: "Karyawan",
        minorRole: "Marketing",
        date: "2025-10-21",
        checkIn: "08:00",
        checkOut: "17:15",
    },
    {
        id: "User-005-RizkyHidayat",
        name: "Rizky Hidayat",
        workStatus: "Work From Office",
        majorRole: "Manager",
        minorRole: "IT",
        date: "2025-10-21",
        checkIn: "07:45",
        checkOut: "17:30",
    },
    {
        id: "User-006-NurAisyah",
        name: "Nur Aisyah",
        workStatus: "Hybrid",
        majorRole: "Karyawan",
        minorRole: "Design",
        date: "2025-10-21",
        checkIn: "08:20",
        checkOut: "17:00",
    },
    {
        id: "User-007-FajarPratama",
        name: "Fajar Pratama",
        workStatus: "Work From Office",
        majorRole: "Karyawan",
        minorRole: "Development",
        date: "2025-10-21",
        checkIn: "07:50",
        checkOut: "17:10",
    },
    {
        id: "User-008-MayaPutri",
        name: "Maya Putri",
        workStatus: "Work From Home",
        majorRole: "Karyawan",
        minorRole: "Customer Support",
        date: "2025-10-21",
        checkIn: "08:05",
        checkOut: "17:05",
    },
    {
        id: "User-001-BudiSantoso-002",
        name: "Budi Santoso",
        workStatus: "Work From Home",
        majorRole: "Karyawan",
        minorRole: "HR",
        date: "2025-10-27",
        checkIn: "08:02",
        checkOut: "17:00",
    },
];