import { Absensi, MajorRole, MinorRole, WorkStatus } from "../types/types";

export const dummyAbsensi: Absensi[] = [
    {
        id: "User-001-BudiSantoso",
        name: "Budi Santoso",
        workStatus: WorkStatus.WFO,
        majorRole: MajorRole.KARYAWAN,
        minorRole: MinorRole.BACKEND,
        date: "2025-10-21",
        checkIn: "08:02",
        checkOut: "17:00",
    },
    {
        id: "User-002-SitiRahmawati",
        name: "Siti Rahmawati",
        workStatus: WorkStatus.WFO,
        majorRole: MajorRole.KARYAWAN,
        minorRole: MinorRole.BACKEND,
        date: "2025-10-21",
        checkIn: "07:55",
        checkOut: "16:45",
    },
    {
        id: "User-003-AhmadFauzi",
        name: "Ahmad Fauzi",
        workStatus: WorkStatus.HYBRID,
        majorRole: MajorRole.KARYAWAN,
        minorRole: MinorRole.BACKEND,
        date: "2025-10-21",
        checkIn: "08:10",
        checkOut: "17:05",
    },
    {
        id: "User-004-DewiLestari",
        name: "Dewi Lestari",
        workStatus: WorkStatus.WFH,
        majorRole: MajorRole.KARYAWAN,
        minorRole: MinorRole.FRONTEND,
        date: "2025-10-21",
        checkIn: "08:00",
        checkOut: "17:15",
    },
    {
        id: "User-005-RizkyHidayat",
        name: "Rizky Hidayat",
        workStatus: WorkStatus.WFH,
        majorRole: MajorRole.KARYAWAN,
        minorRole: MinorRole.FRONTEND,
        date: "2025-10-21",
        checkIn: "07:45",
        checkOut: "17:30",
    },
    {
        id: "User-006-NurAisyah",
        name: "Nur Aisyah",
        workStatus: WorkStatus.HYBRID,
        majorRole: MajorRole.KARYAWAN,
        minorRole: MinorRole.FRONTEND,
        date: "2025-10-21",
        checkIn: "08:20",
        checkOut: "17:00",
    },
    {
        id: "User-007-FajarPratama",
        name: "Fajar Pratama",
        workStatus: WorkStatus.WFH,
        majorRole: MajorRole.KARYAWAN,
        minorRole: MinorRole.HR,
        date: "2025-10-21",
        checkIn: "07:50",
        checkOut: "17:10",
    },
    {
        id: "User-008-MayaPutri",
        name: "Maya Putri",
        workStatus: WorkStatus.WFH,
        majorRole: MajorRole.KARYAWAN,
        minorRole: MinorRole.ADMIN,
        date: "2025-10-21",
        checkIn: "08:05",
        checkOut: "17:05",
    },
    {
        id: "User-001-BudiSantoso-002",
        name: "Budi Santoso",
        workStatus: WorkStatus.WFH,
        majorRole: MajorRole.KARYAWAN,
        minorRole: MinorRole.BACKEND,
        date: "2025-10-27",
        checkIn: "08:02",
        checkOut: "17:00",
    },
];