import { Cuti } from "@/app/lib/types/types";

export const dummyCuti: Cuti[] = [
    {
        id: "C001",
        name: "Andi Pratama",
        branch: "Jakarta",
        startDate: "2025-10-10",
        endDate: "2025-10-14",
        totalDays: 5,
        reason: "Liburan keluarga",
        majorRole: "Karyawan",
        minorRole: "Frontend Developer",
        status: "Diterima",
        approver: "HRD - Sinta Rahmawati",
        submissionDate: "2025-10-05",
    },
    {
        id: "C002",
        name: "Rina Marlina",
        branch: "Bandung",
        startDate: "2025-10-18",
        endDate: "2025-10-20",
        totalDays: 3,
        reason: "Acara keluarga",
        majorRole: "Karyawan",
        minorRole: "UI/UX Designer",
        status: "Menunggu",
        approver: "-",
        submissionDate: "2025-10-15",
    },
    {
        id: "C003",
        name: "Dewi Kartika",
        branch: "Surabaya",
        startDate: "2025-09-25",
        endDate: "2025-09-30",
        totalDays: 6,
        reason: "Sakit",
        majorRole: "Karyawan",
        minorRole: "Backend Developer",
        status: "Diterima",
        approver: "HRD - Sinta Rahmawati",
        submissionDate: "2025-09-24",
    },
    {
        id: "C004",
        name: "Bagus Santoso",
        branch: "Jakarta",
        startDate: "2025-10-02",
        endDate: "2025-10-05",
        totalDays: 4,
        reason: "Menjaga orang tua",
        majorRole: "Karyawan",
        minorRole: "Project Manager",
        status: "Ditolak",
        approver: "HRD - Sinta Rahmawati",
        submissionDate: "2025-09-30",
    },
    {
        id: "C005",
        name: "Lia Anggraini",
        branch: "Medan",
        startDate: "2025-10-22",
        endDate: "2025-10-24",
        totalDays: 3,
        reason: "Pernikahan saudara",
        majorRole: "Karyawan",
        minorRole: "Admin",
        status: "Menunggu",
        approver: "-",
        submissionDate: "2025-10-19",
    },
    {
        id: "C006",
        name: "Andi Pratama",
        branch: "Jakarta",
        startDate: "2025-11-1",
        endDate: "2025-11-3",
        totalDays: 3,
        reason: "Liburan keluarga",
        majorRole: "Karyawan",
        minorRole: "Frontend Developer",
        status: "Diterima",
        approver: "HRD - Sinta Rahmawati",
        submissionDate: "2025-10-27",
    },
];
