import { MajorRole, MinorRole, User } from "@/app/lib/types/types";

export const dummyUsers: User[] = [
  {
    id: "USR001",
    email: "dewi.owner@company.com",
    password: "123456",
    nama: "Dewi Kartika",
    majorRole: MajorRole.OWNER,
    tanggalMulai: "2022-01-01",
    tanggalSelesai: "9999-12-31",
    projectList: [],
  },
  {
    id: "USR002",
    email: "andi.hr@company.com",
    password: "123456",
    nama: "Andi Saputra",
    majorRole: MajorRole.KARYAWAN,
    minorRole: MinorRole.HR,
    tanggalMulai: "2023-02-10",
    tanggalSelesai: "9999-12-31",
    projectList: [],
  },
  {
    id: "USR003",
    email: "rafi.pm@company.com",
    password: "123456",
    nama: "Rafi Ramadhan",
    majorRole: MajorRole.KARYAWAN,
    minorRole: MinorRole.PROJECT_MANAGER,
    tanggalMulai: "2023-03-05",
    tanggalSelesai: "9999-12-31",
    projectList: [
      { projectId: "PRJ001", projectName: "Sistem Manajemen Karyawan" },
      { projectId: "PRJ002", projectName: "Aplikasi Penilaian Kinerja" },
    ],
  },
  {
    id: "USR004",
    email: "budi.uiux@company.com",
    password: "123456",
    nama: "Budi Santoso",
    majorRole: MajorRole.KARYAWAN,
    minorRole: MinorRole.UI_UX,
    tanggalMulai: "2023-03-10",
    tanggalSelesai: "9999-12-31",
    projectList: [{ projectId: "PRJ001", projectName: "Sistem Manajemen Karyawan" }],
  },
  {
    id: "USR005",
    email: "citra.frontend@company.com",
    password: "123456",
    nama: "Citra Lestari",
    majorRole: MajorRole.KARYAWAN,
    minorRole: MinorRole.UI_UX,
    tanggalMulai: "2023-03-15",
    tanggalSelesai: "9999-12-31",
    projectList: [
      { projectId: "PRJ001", projectName: "Sistem Manajemen Karyawan" },
      { projectId: "PRJ003", projectName: "Dashboard Keuangan Internal" },
    ],
  },
  {
    id: "USR006",
    email: "fauzan.backend@company.com",
    password: "123456",
    nama: "Fauzan Pratama",
    majorRole: MajorRole.KARYAWAN,
    minorRole: MinorRole.BACKEND,
    tanggalMulai: "2023-04-01",
    tanggalSelesai: "9999-12-31",
    projectList: [
      { projectId: "PRJ001", projectName: "Sistem Manajemen Karyawan" },
      { projectId: "PRJ003", projectName: "Dashboard Keuangan Internal" },
    ],
  },
  {
    id: "USR007",
    email: "intan.pm@company.com",
    password: "123456",
    nama: "Intan Wulandari",
    majorRole: MajorRole.KARYAWAN,
    minorRole: MinorRole.PROJECT_MANAGER,
    tanggalMulai: "2023-05-10",
    tanggalSelesai: "9999-12-31",
    projectList: [{ projectId: "PRJ002", projectName: "Aplikasi Penilaian Kinerja" }],
  },
  {
    id: "USR008",
    email: "siti.uiux@company.com",
    password: "123456",
    nama: "Siti Nurhaliza",
    majorRole: MajorRole.KARYAWAN,
    minorRole: MinorRole.UI_UX,
    tanggalMulai: "2023-05-15",
    tanggalSelesai: "9999-12-31",
    projectList: [
      { projectId: "PRJ002", projectName: "Aplikasi Penilaian Kinerja" },
      { projectId: "PRJ003", projectName: "Dashboard Keuangan Internal" },
    ],
  },
  {
    id: "USR009",
    email: "teguh.frontend@company.com",
    password: "123456",
    nama: "Teguh Mahendra",
    majorRole: MajorRole.KARYAWAN,
    minorRole: MinorRole.FRONTEND,
    tanggalMulai: "2023-05-20",
    tanggalSelesai: "9999-12-31",
    projectList: [{ projectId: "PRJ002", projectName: "Aplikasi Penilaian Kinerja" }],
  },
];
