import { Gaji } from "../types/types";

export const dummyGaji: Gaji[] = [
    {
        id: "GJ-001",
        name: "Budi Santoso",
        minorRole: "Software Engineer",
        branch: "Jakarta",
        month: "Oktober 2025",
        dueDate: "2025-10-25",
        paymentDate: null,
        status: "Belum Dibayar",
        amount: 8500000,
    },
    {
        id: "GJ-002",
        name: "Siti Rahmawati",
        minorRole: "UI/UX Designer",
        branch: "Bandung",
        month: "Oktober 2025",
        dueDate: "2025-10-22",
        paymentDate: "2025-10-20",
        status: "Dibayar",
        amount: 7800000,
    },
    {
        id: "GJ-003",
        name: "Andi Prasetyo",
        minorRole: "HR Officer",
        branch: "Semarang",
        month: "September 2025",
        dueDate: "2025-09-25",
        paymentDate: null,
        status: "Terlambat",
        amount: 6200000,
    },
    {
        id: "GJ-004",
        name: "Dewi Kartika",
        minorRole: "Project Manager",
        branch: "Jakarta",
        month: "Oktober 2025",
        dueDate: "2025-10-24",
        paymentDate: null,
        status: "Belum Dibayar",
        amount: 11000000,
    },
];
