import { KontrakKerja } from "../types/types";

export const dummyKontrakKerja: KontrakKerja[] = 
[
    {
        id: "KK001",
        namaFreelance: "Rizky Adi",
        projectId: "PRJ001",
        projectName: "Redesign Website Marketing",
        role: "UI/UX Designer",
        branch: "Jakarta",
        tanggalMulai: "2025-01-10",
        tanggalSelesai: "2025-03-30",
        totalBayaran: 15000000,
        metodePembayaran: "Termin",
        pembayaran: [
            {
                id: "PAY001",
                termin: 1,
                persentase: 10,
                jumlah: 1500000,
                tanggalJatuhTempo: "2025-01-15",
                tanggalBayar: "2025-01-14",
                status: "Dibayar",
            },
            {
                id: "PAY002",
                termin: 2,
                persentase: 90,
                jumlah: 13500000,
                tanggalJatuhTempo: "2025-03-30",
                status: "Belum Dibayar",
            },
        ],
        status: "Aktif",
        catatan: "Kontrak 3 bulan, pembayaran 10% DP dan 90% pelunasan setelah project selesai.",
    },
    {
        id: "KK002",
        namaFreelance: "Dinda Pratiwi",
        projectId: "PRJ002",
        projectName: "Mobile App Internal Tools",
        role: "Flutter Developer",
        branch: "Bandung",
        tanggalMulai: "2025-02-01",
        tanggalSelesai: "2025-05-30",
        totalBayaran: 20000000,
        metodePembayaran: "Bulanan",
        pembayaran: [
            {
                id: "PAY003",
                termin: 1,
                persentase: 33.3,
                jumlah: 6666666,
                tanggalJatuhTempo: "2025-03-01",
                tanggalBayar: "2025-03-02",
                status: "Dibayar",
            },
            {
                id: "PAY004",
                termin: 2,
                persentase: 33.3,
                jumlah: 6666666,
                tanggalJatuhTempo: "2025-04-01",
                status: "Belum Dibayar",
            },
            {
                id: "PAY005",
                termin: 3,
                persentase: 33.3,
                jumlah: 6666666,
                tanggalJatuhTempo: "2025-05-01",
                status: "Belum Dibayar",
            },
        ],
        status: "Aktif",
    },
    {
        id: "KK003",
        namaFreelance: "Andi Saputra",
        projectId: "PRJ003",
        projectName: "Company Profile Website",
        role: "Frontend Developer",
        branch: "Yogyakarta",
        tanggalMulai: "2024-09-01",
        tanggalSelesai: "2024-12-01",
        totalBayaran: 12000000,
        metodePembayaran: "Full",
        pembayaran: [
            {
                id: "PAY006",
                termin: 1,
                persentase: 100,
                jumlah: 12000000,
                tanggalJatuhTempo: "2024-12-01",
                tanggalBayar: "2024-12-01",
                status: "Dibayar",
            },
        ],
        status: "Selesai",
    },
];
